package com.citytk.dao;

import com.citytk.pojo.TpUsers;

public interface TpUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    int insert(TpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    int insertSelective(TpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    TpUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpUsers record);
}