package com.citytk.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class TpUsers implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.paypwd
     *
     * @mbggenerated
     */
    private String paypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.sex
     *
     * @mbggenerated
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.birthday
     *
     * @mbggenerated
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.user_money
     *
     * @mbggenerated
     */
    private BigDecimal userMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.frozen_money
     *
     * @mbggenerated
     */
    private BigDecimal frozenMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.distribut_money
     *
     * @mbggenerated
     */
    private BigDecimal distributMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.underling_number
     *
     * @mbggenerated
     */
    private Integer underlingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.pay_points
     *
     * @mbggenerated
     */
    private Integer payPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.reg_time
     *
     * @mbggenerated
     */
    private Integer regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.last_login
     *
     * @mbggenerated
     */
    private Integer lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.last_ip
     *
     * @mbggenerated
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.mobile_validated
     *
     * @mbggenerated
     */
    private Byte mobileValidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.oauth
     *
     * @mbggenerated
     */
    private String oauth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.head_pic
     *
     * @mbggenerated
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.district
     *
     * @mbggenerated
     */
    private Integer district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.email_validated
     *
     * @mbggenerated
     */
    private Boolean emailValidated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.level
     *
     * @mbggenerated
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.total_amount
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.is_lock
     *
     * @mbggenerated
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.is_distribut
     *
     * @mbggenerated
     */
    private Boolean isDistribut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.first_leader
     *
     * @mbggenerated
     */
    private Integer firstLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.second_leader
     *
     * @mbggenerated
     */
    private Integer secondLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.third_leader
     *
     * @mbggenerated
     */
    private Integer thirdLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.message_mask
     *
     * @mbggenerated
     */
    private Boolean messageMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.push_id
     *
     * @mbggenerated
     */
    private String pushId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.distribut_level
     *
     * @mbggenerated
     */
    private Byte distributLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.is_vip
     *
     * @mbggenerated
     */
    private Boolean isVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.invite_code
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.relation
     *
     * @mbggenerated
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.sale_number
     *
     * @mbggenerated
     */
    private Integer saleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.wechat
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.wechat_qrcode
     *
     * @mbggenerated
     */
    private String wechatQrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.set_pass
     *
     * @mbggenerated
     */
    private Boolean setPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.im_id
     *
     * @mbggenerated
     */
    private String imId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.im_pwd
     *
     * @mbggenerated
     */
    private String imPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.is_top
     *
     * @mbggenerated
     */
    private Boolean isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.paper_number
     *
     * @mbggenerated
     */
    private Integer paperNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.paper_number_allowance
     *
     * @mbggenerated
     */
    private Integer paperNumberAllowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.voice_notice
     *
     * @mbggenerated
     */
    private Boolean voiceNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users.backimg
     *
     * @mbggenerated
     */
    private String backimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.user_id
     *
     * @return the value of tp_users.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.user_id
     *
     * @param userId the value for tp_users.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.email
     *
     * @return the value of tp_users.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.email
     *
     * @param email the value for tp_users.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.password
     *
     * @return the value of tp_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.password
     *
     * @param password the value for tp_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.paypwd
     *
     * @return the value of tp_users.paypwd
     *
     * @mbggenerated
     */
    public String getPaypwd() {
        return paypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.paypwd
     *
     * @param paypwd the value for tp_users.paypwd
     *
     * @mbggenerated
     */
    public void setPaypwd(String paypwd) {
        this.paypwd = paypwd == null ? null : paypwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.sex
     *
     * @return the value of tp_users.sex
     *
     * @mbggenerated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.sex
     *
     * @param sex the value for tp_users.sex
     *
     * @mbggenerated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.birthday
     *
     * @return the value of tp_users.birthday
     *
     * @mbggenerated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.birthday
     *
     * @param birthday the value for tp_users.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.user_money
     *
     * @return the value of tp_users.user_money
     *
     * @mbggenerated
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.user_money
     *
     * @param userMoney the value for tp_users.user_money
     *
     * @mbggenerated
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.frozen_money
     *
     * @return the value of tp_users.frozen_money
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.frozen_money
     *
     * @param frozenMoney the value for tp_users.frozen_money
     *
     * @mbggenerated
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.distribut_money
     *
     * @return the value of tp_users.distribut_money
     *
     * @mbggenerated
     */
    public BigDecimal getDistributMoney() {
        return distributMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.distribut_money
     *
     * @param distributMoney the value for tp_users.distribut_money
     *
     * @mbggenerated
     */
    public void setDistributMoney(BigDecimal distributMoney) {
        this.distributMoney = distributMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.underling_number
     *
     * @return the value of tp_users.underling_number
     *
     * @mbggenerated
     */
    public Integer getUnderlingNumber() {
        return underlingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.underling_number
     *
     * @param underlingNumber the value for tp_users.underling_number
     *
     * @mbggenerated
     */
    public void setUnderlingNumber(Integer underlingNumber) {
        this.underlingNumber = underlingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.pay_points
     *
     * @return the value of tp_users.pay_points
     *
     * @mbggenerated
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.pay_points
     *
     * @param payPoints the value for tp_users.pay_points
     *
     * @mbggenerated
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.address_id
     *
     * @return the value of tp_users.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.address_id
     *
     * @param addressId the value for tp_users.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.reg_time
     *
     * @return the value of tp_users.reg_time
     *
     * @mbggenerated
     */
    public Integer getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.reg_time
     *
     * @param regTime the value for tp_users.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Integer regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.last_login
     *
     * @return the value of tp_users.last_login
     *
     * @mbggenerated
     */
    public Integer getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.last_login
     *
     * @param lastLogin the value for tp_users.last_login
     *
     * @mbggenerated
     */
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.last_ip
     *
     * @return the value of tp_users.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.last_ip
     *
     * @param lastIp the value for tp_users.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.qq
     *
     * @return the value of tp_users.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.qq
     *
     * @param qq the value for tp_users.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.mobile
     *
     * @return the value of tp_users.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.mobile
     *
     * @param mobile the value for tp_users.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.mobile_validated
     *
     * @return the value of tp_users.mobile_validated
     *
     * @mbggenerated
     */
    public Byte getMobileValidated() {
        return mobileValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.mobile_validated
     *
     * @param mobileValidated the value for tp_users.mobile_validated
     *
     * @mbggenerated
     */
    public void setMobileValidated(Byte mobileValidated) {
        this.mobileValidated = mobileValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.oauth
     *
     * @return the value of tp_users.oauth
     *
     * @mbggenerated
     */
    public String getOauth() {
        return oauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.oauth
     *
     * @param oauth the value for tp_users.oauth
     *
     * @mbggenerated
     */
    public void setOauth(String oauth) {
        this.oauth = oauth == null ? null : oauth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.openid
     *
     * @return the value of tp_users.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.openid
     *
     * @param openid the value for tp_users.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.unionid
     *
     * @return the value of tp_users.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.unionid
     *
     * @param unionid the value for tp_users.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.head_pic
     *
     * @return the value of tp_users.head_pic
     *
     * @mbggenerated
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.head_pic
     *
     * @param headPic the value for tp_users.head_pic
     *
     * @mbggenerated
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.province
     *
     * @return the value of tp_users.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.province
     *
     * @param province the value for tp_users.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.city
     *
     * @return the value of tp_users.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.city
     *
     * @param city the value for tp_users.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.district
     *
     * @return the value of tp_users.district
     *
     * @mbggenerated
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.district
     *
     * @param district the value for tp_users.district
     *
     * @mbggenerated
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.email_validated
     *
     * @return the value of tp_users.email_validated
     *
     * @mbggenerated
     */
    public Boolean getEmailValidated() {
        return emailValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.email_validated
     *
     * @param emailValidated the value for tp_users.email_validated
     *
     * @mbggenerated
     */
    public void setEmailValidated(Boolean emailValidated) {
        this.emailValidated = emailValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.nickname
     *
     * @return the value of tp_users.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.nickname
     *
     * @param nickname the value for tp_users.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.level
     *
     * @return the value of tp_users.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.level
     *
     * @param level the value for tp_users.level
     *
     * @mbggenerated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.discount
     *
     * @return the value of tp_users.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.discount
     *
     * @param discount the value for tp_users.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.total_amount
     *
     * @return the value of tp_users.total_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.total_amount
     *
     * @param totalAmount the value for tp_users.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.is_lock
     *
     * @return the value of tp_users.is_lock
     *
     * @mbggenerated
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.is_lock
     *
     * @param isLock the value for tp_users.is_lock
     *
     * @mbggenerated
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.is_distribut
     *
     * @return the value of tp_users.is_distribut
     *
     * @mbggenerated
     */
    public Boolean getIsDistribut() {
        return isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.is_distribut
     *
     * @param isDistribut the value for tp_users.is_distribut
     *
     * @mbggenerated
     */
    public void setIsDistribut(Boolean isDistribut) {
        this.isDistribut = isDistribut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.first_leader
     *
     * @return the value of tp_users.first_leader
     *
     * @mbggenerated
     */
    public Integer getFirstLeader() {
        return firstLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.first_leader
     *
     * @param firstLeader the value for tp_users.first_leader
     *
     * @mbggenerated
     */
    public void setFirstLeader(Integer firstLeader) {
        this.firstLeader = firstLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.second_leader
     *
     * @return the value of tp_users.second_leader
     *
     * @mbggenerated
     */
    public Integer getSecondLeader() {
        return secondLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.second_leader
     *
     * @param secondLeader the value for tp_users.second_leader
     *
     * @mbggenerated
     */
    public void setSecondLeader(Integer secondLeader) {
        this.secondLeader = secondLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.third_leader
     *
     * @return the value of tp_users.third_leader
     *
     * @mbggenerated
     */
    public Integer getThirdLeader() {
        return thirdLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.third_leader
     *
     * @param thirdLeader the value for tp_users.third_leader
     *
     * @mbggenerated
     */
    public void setThirdLeader(Integer thirdLeader) {
        this.thirdLeader = thirdLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.token
     *
     * @return the value of tp_users.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.token
     *
     * @param token the value for tp_users.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.message_mask
     *
     * @return the value of tp_users.message_mask
     *
     * @mbggenerated
     */
    public Boolean getMessageMask() {
        return messageMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.message_mask
     *
     * @param messageMask the value for tp_users.message_mask
     *
     * @mbggenerated
     */
    public void setMessageMask(Boolean messageMask) {
        this.messageMask = messageMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.push_id
     *
     * @return the value of tp_users.push_id
     *
     * @mbggenerated
     */
    public String getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.push_id
     *
     * @param pushId the value for tp_users.push_id
     *
     * @mbggenerated
     */
    public void setPushId(String pushId) {
        this.pushId = pushId == null ? null : pushId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.distribut_level
     *
     * @return the value of tp_users.distribut_level
     *
     * @mbggenerated
     */
    public Byte getDistributLevel() {
        return distributLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.distribut_level
     *
     * @param distributLevel the value for tp_users.distribut_level
     *
     * @mbggenerated
     */
    public void setDistributLevel(Byte distributLevel) {
        this.distributLevel = distributLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.is_vip
     *
     * @return the value of tp_users.is_vip
     *
     * @mbggenerated
     */
    public Boolean getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.is_vip
     *
     * @param isVip the value for tp_users.is_vip
     *
     * @mbggenerated
     */
    public void setIsVip(Boolean isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.invite_code
     *
     * @return the value of tp_users.invite_code
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.invite_code
     *
     * @param inviteCode the value for tp_users.invite_code
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.relation
     *
     * @return the value of tp_users.relation
     *
     * @mbggenerated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.relation
     *
     * @param relation the value for tp_users.relation
     *
     * @mbggenerated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.sale_number
     *
     * @return the value of tp_users.sale_number
     *
     * @mbggenerated
     */
    public Integer getSaleNumber() {
        return saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.sale_number
     *
     * @param saleNumber the value for tp_users.sale_number
     *
     * @mbggenerated
     */
    public void setSaleNumber(Integer saleNumber) {
        this.saleNumber = saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.parent_id
     *
     * @return the value of tp_users.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.parent_id
     *
     * @param parentId the value for tp_users.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.wechat
     *
     * @return the value of tp_users.wechat
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.wechat
     *
     * @param wechat the value for tp_users.wechat
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.wechat_qrcode
     *
     * @return the value of tp_users.wechat_qrcode
     *
     * @mbggenerated
     */
    public String getWechatQrcode() {
        return wechatQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.wechat_qrcode
     *
     * @param wechatQrcode the value for tp_users.wechat_qrcode
     *
     * @mbggenerated
     */
    public void setWechatQrcode(String wechatQrcode) {
        this.wechatQrcode = wechatQrcode == null ? null : wechatQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.set_pass
     *
     * @return the value of tp_users.set_pass
     *
     * @mbggenerated
     */
    public Boolean getSetPass() {
        return setPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.set_pass
     *
     * @param setPass the value for tp_users.set_pass
     *
     * @mbggenerated
     */
    public void setSetPass(Boolean setPass) {
        this.setPass = setPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.im_id
     *
     * @return the value of tp_users.im_id
     *
     * @mbggenerated
     */
    public String getImId() {
        return imId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.im_id
     *
     * @param imId the value for tp_users.im_id
     *
     * @mbggenerated
     */
    public void setImId(String imId) {
        this.imId = imId == null ? null : imId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.im_pwd
     *
     * @return the value of tp_users.im_pwd
     *
     * @mbggenerated
     */
    public String getImPwd() {
        return imPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.im_pwd
     *
     * @param imPwd the value for tp_users.im_pwd
     *
     * @mbggenerated
     */
    public void setImPwd(String imPwd) {
        this.imPwd = imPwd == null ? null : imPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.is_top
     *
     * @return the value of tp_users.is_top
     *
     * @mbggenerated
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.is_top
     *
     * @param isTop the value for tp_users.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.paper_number
     *
     * @return the value of tp_users.paper_number
     *
     * @mbggenerated
     */
    public Integer getPaperNumber() {
        return paperNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.paper_number
     *
     * @param paperNumber the value for tp_users.paper_number
     *
     * @mbggenerated
     */
    public void setPaperNumber(Integer paperNumber) {
        this.paperNumber = paperNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.paper_number_allowance
     *
     * @return the value of tp_users.paper_number_allowance
     *
     * @mbggenerated
     */
    public Integer getPaperNumberAllowance() {
        return paperNumberAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.paper_number_allowance
     *
     * @param paperNumberAllowance the value for tp_users.paper_number_allowance
     *
     * @mbggenerated
     */
    public void setPaperNumberAllowance(Integer paperNumberAllowance) {
        this.paperNumberAllowance = paperNumberAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.voice_notice
     *
     * @return the value of tp_users.voice_notice
     *
     * @mbggenerated
     */
    public Boolean getVoiceNotice() {
        return voiceNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.voice_notice
     *
     * @param voiceNotice the value for tp_users.voice_notice
     *
     * @mbggenerated
     */
    public void setVoiceNotice(Boolean voiceNotice) {
        this.voiceNotice = voiceNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users.backimg
     *
     * @return the value of tp_users.backimg
     *
     * @mbggenerated
     */
    public String getBackimg() {
        return backimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users.backimg
     *
     * @param backimg the value for tp_users.backimg
     *
     * @mbggenerated
     */
    public void setBackimg(String backimg) {
        this.backimg = backimg == null ? null : backimg.trim();
    }
}